# Emissary-ingress Mapping to route /faces/ to the faces-gui Service in the
# faces namespace. The faces-gui Service is what serves the HTML for the Faces
# GUI demo; it's the thing you load using your browser.
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: gui-mapping
  namespace: faces
spec:
  hostname: "*"
  prefix: /faces/
  service: faces-gui.faces
  rewrite: /
  timeout_ms: 0
