# Emissary Listeners: accept HTTPS on port 8443 and HTTP on port 8080.
# These container ports line up with the default emissary-ingress Service
# deployed by the Emissary Helm chart.
---
apiVersion: getambassador.io/v3alpha1
kind: Listener
metadata:
  name: ambassador-https-listener
spec:
  port: 8443
  protocol: HTTPS
  securityModel: XFP
  hostBinding:
    namespace:
      from: ALL
---
apiVersion: getambassador.io/v3alpha1
kind: Listener
metadata:
  name: ambassador-http-listener
spec:
  port: 8080
  protocol: HTTP
  securityModel: XFP
  hostBinding:
    namespace:
      from: ALL

# *** INSECURE *** Emissary wildcard Host: accept requests for any hostname,
# and route HTTP rather than redirecting it to HTTPS. In the real world, you'd
# want to define Hosts for the specific hostnames you want, and you'd want
# HTTPS set up as well.
---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: wildcard-host
spec:
  hostname: "*"
  requestPolicy:
    insecure:
      action: Route
